"""add location to profiles

Revision ID: b3855a04e018
Revises: 96c9b7554393
Create Date: 2026-05-02 17:31:22.608350

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "b3855a04e018"
down_revision = "96c9b7554393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(length=150), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_profiles_location"), ["location"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profiles_location"))
        batch_op.drop_column("location")

    # ### end Alembic commands ###
